//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.constraint_2_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eml.ecoinformatics_org.resource_2_1.ScopeType;


/**
 * <p>Java class for ConstraintType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConstraintType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="primaryKey">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
 *                   &lt;element name="key">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uniqueKey">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
 *                   &lt;element name="key">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="checkConstraint">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
 *                   &lt;element name="checkCondition" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="foreignKey">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ForeignKeyGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="joinCondition">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ForeignKeyGroup"/>
 *                   &lt;element name="referencedKey">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="notNullConstraint">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
 *                   &lt;element name="key">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{eml://ecoinformatics.org/resource-2.1.1}IDType" />
 *       &lt;attribute name="system" type="{eml://ecoinformatics.org/resource-2.1.1}SystemType" />
 *       &lt;attribute name="scope" type="{eml://ecoinformatics.org/resource-2.1.1}ScopeType" default="document" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConstraintType", propOrder = {
    "primaryKey",
    "uniqueKey",
    "checkConstraint",
    "foreignKey",
    "joinCondition",
    "notNullConstraint"
})
public class ConstraintType {

    protected ConstraintType.PrimaryKey primaryKey;
    protected ConstraintType.UniqueKey uniqueKey;
    protected ConstraintType.CheckConstraint checkConstraint;
    protected ConstraintType.ForeignKey foreignKey;
    protected ConstraintType.JoinCondition joinCondition;
    protected ConstraintType.NotNullConstraint notNullConstraint;
    @XmlAttribute(name = "id")
    protected List<String> id;
    @XmlAttribute(name = "system")
    protected List<String> system;
    @XmlAttribute(name = "scope")
    protected ScopeType scope;

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintType.PrimaryKey }
     *     
     */
    public ConstraintType.PrimaryKey getPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintType.PrimaryKey }
     *     
     */
    public void setPrimaryKey(ConstraintType.PrimaryKey value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the uniqueKey property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintType.UniqueKey }
     *     
     */
    public ConstraintType.UniqueKey getUniqueKey() {
        return uniqueKey;
    }

    /**
     * Sets the value of the uniqueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintType.UniqueKey }
     *     
     */
    public void setUniqueKey(ConstraintType.UniqueKey value) {
        this.uniqueKey = value;
    }

    /**
     * Gets the value of the checkConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintType.CheckConstraint }
     *     
     */
    public ConstraintType.CheckConstraint getCheckConstraint() {
        return checkConstraint;
    }

    /**
     * Sets the value of the checkConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintType.CheckConstraint }
     *     
     */
    public void setCheckConstraint(ConstraintType.CheckConstraint value) {
        this.checkConstraint = value;
    }

    /**
     * Gets the value of the foreignKey property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintType.ForeignKey }
     *     
     */
    public ConstraintType.ForeignKey getForeignKey() {
        return foreignKey;
    }

    /**
     * Sets the value of the foreignKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintType.ForeignKey }
     *     
     */
    public void setForeignKey(ConstraintType.ForeignKey value) {
        this.foreignKey = value;
    }

    /**
     * Gets the value of the joinCondition property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintType.JoinCondition }
     *     
     */
    public ConstraintType.JoinCondition getJoinCondition() {
        return joinCondition;
    }

    /**
     * Sets the value of the joinCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintType.JoinCondition }
     *     
     */
    public void setJoinCondition(ConstraintType.JoinCondition value) {
        this.joinCondition = value;
    }

    /**
     * Gets the value of the notNullConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintType.NotNullConstraint }
     *     
     */
    public ConstraintType.NotNullConstraint getNotNullConstraint() {
        return notNullConstraint;
    }

    /**
     * Sets the value of the notNullConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintType.NotNullConstraint }
     *     
     */
    public void setNotNullConstraint(ConstraintType.NotNullConstraint value) {
        this.notNullConstraint = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getId() {
        if (id == null) {
            id = new ArrayList<String>();
        }
        return this.id;
    }

    /**
     * Gets the value of the system property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the system property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSystem() {
        if (system == null) {
            system = new ArrayList<String>();
        }
        return this.system;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link ScopeType }
     *     
     */
    public ScopeType getScope() {
        if (scope == null) {
            return ScopeType.DOCUMENT;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopeType }
     *     
     */
    public void setScope(ScopeType value) {
        this.scope = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
     *         &lt;element name="checkCondition" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraintName",
        "constraintDescription",
        "checkCondition"
    })
    public static class CheckConstraint {

        @XmlElement(required = true)
        protected String constraintName;
        protected Object constraintDescription;
        @XmlElement(required = true)
        protected String checkCondition;
        @XmlAttribute(name = "language")
        protected String language;

        /**
         * Gets the value of the constraintName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstraintName() {
            return constraintName;
        }

        /**
         * Sets the value of the constraintName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstraintName(String value) {
            this.constraintName = value;
        }

        /**
         * Gets the value of the constraintDescription property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getConstraintDescription() {
            return constraintDescription;
        }

        /**
         * Sets the value of the constraintDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setConstraintDescription(Object value) {
            this.constraintDescription = value;
        }

        /**
         * Gets the value of the checkCondition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCheckCondition() {
            return checkCondition;
        }

        /**
         * Sets the value of the checkCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCheckCondition(String value) {
            this.checkCondition = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ForeignKeyGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraintName",
        "constraintDescription",
        "key",
        "entityReference",
        "relationshipType",
        "cardinality"
    })
    public static class ForeignKey {

        @XmlElement(required = true)
        protected String constraintName;
        protected Object constraintDescription;
        @XmlElement(required = true)
        protected ConstraintType.JoinCondition.Key key;
        @XmlElement(required = true)
        protected String entityReference;
        protected String relationshipType;
        protected ConstraintType.JoinCondition.Cardinality cardinality;

        /**
         * Gets the value of the constraintName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstraintName() {
            return constraintName;
        }

        /**
         * Sets the value of the constraintName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstraintName(String value) {
            this.constraintName = value;
        }

        /**
         * Gets the value of the constraintDescription property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getConstraintDescription() {
            return constraintDescription;
        }

        /**
         * Sets the value of the constraintDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setConstraintDescription(Object value) {
            this.constraintDescription = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.JoinCondition.Key }
         *     
         */
        public ConstraintType.JoinCondition.Key getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.JoinCondition.Key }
         *     
         */
        public void setKey(ConstraintType.JoinCondition.Key value) {
            this.key = value;
        }

        /**
         * Gets the value of the entityReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntityReference() {
            return entityReference;
        }

        /**
         * Sets the value of the entityReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntityReference(String value) {
            this.entityReference = value;
        }

        /**
         * Gets the value of the relationshipType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelationshipType() {
            return relationshipType;
        }

        /**
         * Sets the value of the relationshipType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelationshipType(String value) {
            this.relationshipType = value;
        }

        /**
         * Gets the value of the cardinality property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.JoinCondition.Cardinality }
         *     
         */
        public ConstraintType.JoinCondition.Cardinality getCardinality() {
            return cardinality;
        }

        /**
         * Sets the value of the cardinality property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.JoinCondition.Cardinality }
         *     
         */
        public void setCardinality(ConstraintType.JoinCondition.Cardinality value) {
            this.cardinality = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ForeignKeyGroup"/>
     *         &lt;element name="referencedKey">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraintName",
        "constraintDescription",
        "key",
        "entityReference",
        "relationshipType",
        "cardinality",
        "referencedKey"
    })
    public static class JoinCondition {

        @XmlElement(required = true)
        protected String constraintName;
        protected Object constraintDescription;
        @XmlElement(required = true)
        protected ConstraintType.JoinCondition.Key key;
        @XmlElement(required = true)
        protected String entityReference;
        protected String relationshipType;
        protected ConstraintType.JoinCondition.Cardinality cardinality;
        @XmlElement(required = true)
        protected ConstraintType.JoinCondition.ReferencedKey referencedKey;

        /**
         * Gets the value of the constraintName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstraintName() {
            return constraintName;
        }

        /**
         * Sets the value of the constraintName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstraintName(String value) {
            this.constraintName = value;
        }

        /**
         * Gets the value of the constraintDescription property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getConstraintDescription() {
            return constraintDescription;
        }

        /**
         * Sets the value of the constraintDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setConstraintDescription(Object value) {
            this.constraintDescription = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.JoinCondition.Key }
         *     
         */
        public ConstraintType.JoinCondition.Key getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.JoinCondition.Key }
         *     
         */
        public void setKey(ConstraintType.JoinCondition.Key value) {
            this.key = value;
        }

        /**
         * Gets the value of the entityReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntityReference() {
            return entityReference;
        }

        /**
         * Sets the value of the entityReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntityReference(String value) {
            this.entityReference = value;
        }

        /**
         * Gets the value of the relationshipType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelationshipType() {
            return relationshipType;
        }

        /**
         * Sets the value of the relationshipType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelationshipType(String value) {
            this.relationshipType = value;
        }

        /**
         * Gets the value of the cardinality property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.JoinCondition.Cardinality }
         *     
         */
        public ConstraintType.JoinCondition.Cardinality getCardinality() {
            return cardinality;
        }

        /**
         * Sets the value of the cardinality property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.JoinCondition.Cardinality }
         *     
         */
        public void setCardinality(ConstraintType.JoinCondition.Cardinality value) {
            this.cardinality = value;
        }

        /**
         * Gets the value of the referencedKey property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.JoinCondition.ReferencedKey }
         *     
         */
        public ConstraintType.JoinCondition.ReferencedKey getReferencedKey() {
            return referencedKey;
        }

        /**
         * Sets the value of the referencedKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.JoinCondition.ReferencedKey }
         *     
         */
        public void setReferencedKey(ConstraintType.JoinCondition.ReferencedKey value) {
            this.referencedKey = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="parentOccurences">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;enumeration value="0"/>
         *               &lt;enumeration value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="childOccurences" type="{eml://ecoinformatics.org/constraint-2.1.1}CardinalityChildOccurancesType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "parentOccurences",
            "childOccurences"
        })
        public static class Cardinality {

            @XmlElement(required = true)
            protected BigInteger parentOccurences;
            @XmlElement(required = true)
            protected String childOccurences;

            /**
             * Gets the value of the parentOccurences property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getParentOccurences() {
                return parentOccurences;
            }

            /**
             * Sets the value of the parentOccurences property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setParentOccurences(BigInteger value) {
                this.parentOccurences = value;
            }

            /**
             * Gets the value of the childOccurences property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChildOccurences() {
                return childOccurences;
            }

            /**
             * Sets the value of the childOccurences property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChildOccurences(String value) {
                this.childOccurences = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeReference"
        })
        public static class Key {

            @XmlElement(required = true)
            protected List<String> attributeReference;

            /**
             * Gets the value of the attributeReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAttributeReference() {
                if (attributeReference == null) {
                    attributeReference = new ArrayList<String>();
                }
                return this.attributeReference;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeReference"
        })
        public static class ReferencedKey {

            @XmlElement(required = true)
            protected List<String> attributeReference;

            /**
             * Gets the value of the attributeReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAttributeReference() {
                if (attributeReference == null) {
                    attributeReference = new ArrayList<String>();
                }
                return this.attributeReference;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
     *         &lt;element name="key">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraintName",
        "constraintDescription",
        "key"
    })
    public static class NotNullConstraint {

        @XmlElement(required = true)
        protected String constraintName;
        protected Object constraintDescription;
        @XmlElement(required = true)
        protected ConstraintType.NotNullConstraint.Key key;

        /**
         * Gets the value of the constraintName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstraintName() {
            return constraintName;
        }

        /**
         * Sets the value of the constraintName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstraintName(String value) {
            this.constraintName = value;
        }

        /**
         * Gets the value of the constraintDescription property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getConstraintDescription() {
            return constraintDescription;
        }

        /**
         * Sets the value of the constraintDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setConstraintDescription(Object value) {
            this.constraintDescription = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.NotNullConstraint.Key }
         *     
         */
        public ConstraintType.NotNullConstraint.Key getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.NotNullConstraint.Key }
         *     
         */
        public void setKey(ConstraintType.NotNullConstraint.Key value) {
            this.key = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeReference"
        })
        public static class Key {

            @XmlElement(required = true)
            protected List<String> attributeReference;

            /**
             * Gets the value of the attributeReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAttributeReference() {
                if (attributeReference == null) {
                    attributeReference = new ArrayList<String>();
                }
                return this.attributeReference;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
     *         &lt;element name="key">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraintName",
        "constraintDescription",
        "key"
    })
    public static class PrimaryKey {

        @XmlElement(required = true)
        protected String constraintName;
        protected Object constraintDescription;
        @XmlElement(required = true)
        protected ConstraintType.PrimaryKey.Key key;

        /**
         * Gets the value of the constraintName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstraintName() {
            return constraintName;
        }

        /**
         * Sets the value of the constraintName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstraintName(String value) {
            this.constraintName = value;
        }

        /**
         * Gets the value of the constraintDescription property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getConstraintDescription() {
            return constraintDescription;
        }

        /**
         * Sets the value of the constraintDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setConstraintDescription(Object value) {
            this.constraintDescription = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.PrimaryKey.Key }
         *     
         */
        public ConstraintType.PrimaryKey.Key getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.PrimaryKey.Key }
         *     
         */
        public void setKey(ConstraintType.PrimaryKey.Key value) {
            this.key = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeReference"
        })
        public static class Key {

            @XmlElement(required = true)
            protected List<String> attributeReference;

            /**
             * Gets the value of the attributeReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAttributeReference() {
                if (attributeReference == null) {
                    attributeReference = new ArrayList<String>();
                }
                return this.attributeReference;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintBaseGroup"/>
     *         &lt;element name="key">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraintName",
        "constraintDescription",
        "key"
    })
    public static class UniqueKey {

        @XmlElement(required = true)
        protected String constraintName;
        protected Object constraintDescription;
        @XmlElement(required = true)
        protected ConstraintType.UniqueKey.Key key;

        /**
         * Gets the value of the constraintName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstraintName() {
            return constraintName;
        }

        /**
         * Sets the value of the constraintName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstraintName(String value) {
            this.constraintName = value;
        }

        /**
         * Gets the value of the constraintDescription property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getConstraintDescription() {
            return constraintDescription;
        }

        /**
         * Sets the value of the constraintDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setConstraintDescription(Object value) {
            this.constraintDescription = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link ConstraintType.UniqueKey.Key }
         *     
         */
        public ConstraintType.UniqueKey.Key getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConstraintType.UniqueKey.Key }
         *     
         */
        public void setKey(ConstraintType.UniqueKey.Key value) {
            this.key = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="attributeReference" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attributeReference"
        })
        public static class Key {

            @XmlElement(required = true)
            protected List<String> attributeReference;

            /**
             * Gets the value of the attributeReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attributeReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttributeReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAttributeReference() {
                if (attributeReference == null) {
                    attributeReference = new ArrayList<String>();
                }
                return this.attributeReference;
            }

        }

    }

}
