//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.constraint_2_1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.constraint_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.constraint_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link ConstraintType.NotNullConstraint }
     * 
     */
    public ConstraintType.NotNullConstraint createConstraintTypeNotNullConstraint() {
        return new ConstraintType.NotNullConstraint();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition }
     * 
     */
    public ConstraintType.JoinCondition createConstraintTypeJoinCondition() {
        return new ConstraintType.JoinCondition();
    }

    /**
     * Create an instance of {@link ConstraintType.UniqueKey }
     * 
     */
    public ConstraintType.UniqueKey createConstraintTypeUniqueKey() {
        return new ConstraintType.UniqueKey();
    }

    /**
     * Create an instance of {@link ConstraintType.PrimaryKey }
     * 
     */
    public ConstraintType.PrimaryKey createConstraintTypePrimaryKey() {
        return new ConstraintType.PrimaryKey();
    }

    /**
     * Create an instance of {@link ConstraintType.CheckConstraint }
     * 
     */
    public ConstraintType.CheckConstraint createConstraintTypeCheckConstraint() {
        return new ConstraintType.CheckConstraint();
    }

    /**
     * Create an instance of {@link ConstraintType.ForeignKey }
     * 
     */
    public ConstraintType.ForeignKey createConstraintTypeForeignKey() {
        return new ConstraintType.ForeignKey();
    }

    /**
     * Create an instance of {@link ConstraintType.NotNullConstraint.Key }
     * 
     */
    public ConstraintType.NotNullConstraint.Key createConstraintTypeNotNullConstraintKey() {
        return new ConstraintType.NotNullConstraint.Key();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition.Key }
     * 
     */
    public ConstraintType.JoinCondition.Key createConstraintTypeJoinConditionKey() {
        return new ConstraintType.JoinCondition.Key();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition.Cardinality }
     * 
     */
    public ConstraintType.JoinCondition.Cardinality createConstraintTypeJoinConditionCardinality() {
        return new ConstraintType.JoinCondition.Cardinality();
    }

    /**
     * Create an instance of {@link ConstraintType.JoinCondition.ReferencedKey }
     * 
     */
    public ConstraintType.JoinCondition.ReferencedKey createConstraintTypeJoinConditionReferencedKey() {
        return new ConstraintType.JoinCondition.ReferencedKey();
    }

    /**
     * Create an instance of {@link ConstraintType.UniqueKey.Key }
     * 
     */
    public ConstraintType.UniqueKey.Key createConstraintTypeUniqueKeyKey() {
        return new ConstraintType.UniqueKey.Key();
    }

    /**
     * Create an instance of {@link ConstraintType.PrimaryKey.Key }
     * 
     */
    public ConstraintType.PrimaryKey.Key createConstraintTypePrimaryKeyKey() {
        return new ConstraintType.PrimaryKey.Key();
    }

}
