//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.attribute_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Accuracy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Accuracy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributeAccuracyReport" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *         &lt;element name="quantitativeAttributeAccuracyAssessment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attributeAccuracyValue" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *                   &lt;element name="attributeAccuracyExplanation" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Accuracy", propOrder = {
    "attributeAccuracyReport",
    "quantitativeAttributeAccuracyAssessment"
})
public class Accuracy {

    @XmlElement(required = true)
    protected String attributeAccuracyReport;
    protected List<Accuracy.QuantitativeAttributeAccuracyAssessment> quantitativeAttributeAccuracyAssessment;

    /**
     * Gets the value of the attributeAccuracyReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeAccuracyReport() {
        return attributeAccuracyReport;
    }

    /**
     * Sets the value of the attributeAccuracyReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeAccuracyReport(String value) {
        this.attributeAccuracyReport = value;
    }

    /**
     * Gets the value of the quantitativeAttributeAccuracyAssessment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quantitativeAttributeAccuracyAssessment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuantitativeAttributeAccuracyAssessment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accuracy.QuantitativeAttributeAccuracyAssessment }
     * 
     * 
     */
    public List<Accuracy.QuantitativeAttributeAccuracyAssessment> getQuantitativeAttributeAccuracyAssessment() {
        if (quantitativeAttributeAccuracyAssessment == null) {
            quantitativeAttributeAccuracyAssessment = new ArrayList<Accuracy.QuantitativeAttributeAccuracyAssessment>();
        }
        return this.quantitativeAttributeAccuracyAssessment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attributeAccuracyValue" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
     *         &lt;element name="attributeAccuracyExplanation" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeAccuracyValue",
        "attributeAccuracyExplanation"
    })
    public static class QuantitativeAttributeAccuracyAssessment {

        @XmlElement(required = true)
        protected String attributeAccuracyValue;
        @XmlElement(required = true)
        protected String attributeAccuracyExplanation;

        /**
         * Gets the value of the attributeAccuracyValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttributeAccuracyValue() {
            return attributeAccuracyValue;
        }

        /**
         * Sets the value of the attributeAccuracyValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttributeAccuracyValue(String value) {
            this.attributeAccuracyValue = value;
        }

        /**
         * Gets the value of the attributeAccuracyExplanation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttributeAccuracyExplanation() {
            return attributeAccuracyExplanation;
        }

        /**
         * Sets the value of the attributeAccuracyExplanation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttributeAccuracyExplanation(String value) {
            this.attributeAccuracyExplanation = value;
        }

    }

}
