//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.attribute_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.attribute_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Attribute_QNAME = new QName("eml://ecoinformatics.org/attribute-2.1.1", "attribute");
    private final static QName _AttributeList_QNAME = new QName("eml://ecoinformatics.org/attribute-2.1.1", "attributeList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.attribute_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NumericDomainType }
     * 
     */
    public NumericDomainType createNumericDomainType() {
        return new NumericDomainType();
    }

    /**
     * Create an instance of {@link NumericDomainType.Bounds }
     * 
     */
    public NumericDomainType.Bounds createNumericDomainTypeBounds() {
        return new NumericDomainType.Bounds();
    }

    /**
     * Create an instance of {@link DateTimeDomainType }
     * 
     */
    public DateTimeDomainType createDateTimeDomainType() {
        return new DateTimeDomainType();
    }

    /**
     * Create an instance of {@link DateTimeDomainType.Bounds }
     * 
     */
    public DateTimeDomainType.Bounds createDateTimeDomainTypeBounds() {
        return new DateTimeDomainType.Bounds();
    }

    /**
     * Create an instance of {@link Accuracy }
     * 
     */
    public Accuracy createAccuracy() {
        return new Accuracy();
    }

    /**
     * Create an instance of {@link NonNumericDomainType }
     * 
     */
    public NonNumericDomainType createNonNumericDomainType() {
        return new NonNumericDomainType();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain createNonNumericDomainTypeEnumeratedDomain() {
        return new NonNumericDomainType.EnumeratedDomain();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale }
     * 
     */
    public AttributeType.MeasurementScale createAttributeTypeMeasurementScale() {
        return new AttributeType.MeasurementScale();
    }

    /**
     * Create an instance of {@link AttributeListType }
     * 
     */
    public AttributeListType createAttributeListType() {
        return new AttributeListType();
    }

    /**
     * Create an instance of {@link PrecisionType }
     * 
     */
    public PrecisionType createPrecisionType() {
        return new PrecisionType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link NumericDomainType.Bounds.Minimum }
     * 
     */
    public NumericDomainType.Bounds.Minimum createNumericDomainTypeBoundsMinimum() {
        return new NumericDomainType.Bounds.Minimum();
    }

    /**
     * Create an instance of {@link NumericDomainType.Bounds.Maximum }
     * 
     */
    public NumericDomainType.Bounds.Maximum createNumericDomainTypeBoundsMaximum() {
        return new NumericDomainType.Bounds.Maximum();
    }

    /**
     * Create an instance of {@link DateTimeDomainType.Bounds.Minimum }
     * 
     */
    public DateTimeDomainType.Bounds.Minimum createDateTimeDomainTypeBoundsMinimum() {
        return new DateTimeDomainType.Bounds.Minimum();
    }

    /**
     * Create an instance of {@link DateTimeDomainType.Bounds.Maximum }
     * 
     */
    public DateTimeDomainType.Bounds.Maximum createDateTimeDomainTypeBoundsMaximum() {
        return new DateTimeDomainType.Bounds.Maximum();
    }

    /**
     * Create an instance of {@link Accuracy.QuantitativeAttributeAccuracyAssessment }
     * 
     */
    public Accuracy.QuantitativeAttributeAccuracyAssessment createAccuracyQuantitativeAttributeAccuracyAssessment() {
        return new Accuracy.QuantitativeAttributeAccuracyAssessment();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.TextDomain }
     * 
     */
    public NonNumericDomainType.TextDomain createNonNumericDomainTypeTextDomain() {
        return new NonNumericDomainType.TextDomain();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain.CodeDefinition }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain.CodeDefinition createNonNumericDomainTypeEnumeratedDomainCodeDefinition() {
        return new NonNumericDomainType.EnumeratedDomain.CodeDefinition();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain.ExternalCodeSet }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain.ExternalCodeSet createNonNumericDomainTypeEnumeratedDomainExternalCodeSet() {
        return new NonNumericDomainType.EnumeratedDomain.ExternalCodeSet();
    }

    /**
     * Create an instance of {@link NonNumericDomainType.EnumeratedDomain.EntityCodeList }
     * 
     */
    public NonNumericDomainType.EnumeratedDomain.EntityCodeList createNonNumericDomainTypeEnumeratedDomainEntityCodeList() {
        return new NonNumericDomainType.EnumeratedDomain.EntityCodeList();
    }

    /**
     * Create an instance of {@link AttributeType.StorageType }
     * 
     */
    public AttributeType.StorageType createAttributeTypeStorageType() {
        return new AttributeType.StorageType();
    }

    /**
     * Create an instance of {@link AttributeType.MissingValueCode }
     * 
     */
    public AttributeType.MissingValueCode createAttributeTypeMissingValueCode() {
        return new AttributeType.MissingValueCode();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Nominal }
     * 
     */
    public AttributeType.MeasurementScale.Nominal createAttributeTypeMeasurementScaleNominal() {
        return new AttributeType.MeasurementScale.Nominal();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Ordinal }
     * 
     */
    public AttributeType.MeasurementScale.Ordinal createAttributeTypeMeasurementScaleOrdinal() {
        return new AttributeType.MeasurementScale.Ordinal();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Interval }
     * 
     */
    public AttributeType.MeasurementScale.Interval createAttributeTypeMeasurementScaleInterval() {
        return new AttributeType.MeasurementScale.Interval();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.Ratio }
     * 
     */
    public AttributeType.MeasurementScale.Ratio createAttributeTypeMeasurementScaleRatio() {
        return new AttributeType.MeasurementScale.Ratio();
    }

    /**
     * Create an instance of {@link AttributeType.MeasurementScale.DateTime }
     * 
     */
    public AttributeType.MeasurementScale.DateTime createAttributeTypeMeasurementScaleDateTime() {
        return new AttributeType.MeasurementScale.DateTime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/attribute-2.1.1", name = "attribute")
    public JAXBElement<AttributeType> createAttribute(AttributeType value) {
        return new JAXBElement<AttributeType>(_Attribute_QNAME, AttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/attribute-2.1.1", name = "attributeList")
    public JAXBElement<AttributeListType> createAttributeList(AttributeListType value) {
        return new JAXBElement<AttributeListType>(_AttributeList_QNAME, AttributeListType.class, null, value);
    }

}
