//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.resource_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.resource_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _I18NNonEmptyStringTypeValue_QNAME = new QName("", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.resource_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link I18NNonEmptyStringType }
     * 
     */
    public I18NNonEmptyStringType createI18NNonEmptyStringType() {
        return new I18NNonEmptyStringType();
    }

    /**
     * Create an instance of {@link ConnectionDefinitionType }
     * 
     */
    public ConnectionDefinitionType createConnectionDefinitionType() {
        return new ConnectionDefinitionType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link UrlType }
     * 
     */
    public UrlType createUrlType() {
        return new UrlType();
    }

    /**
     * Create an instance of {@link InlineType }
     * 
     */
    public InlineType createInlineType() {
        return new InlineType();
    }

    /**
     * Create an instance of {@link DistributionType }
     * 
     */
    public DistributionType createDistributionType() {
        return new DistributionType();
    }

    /**
     * Create an instance of {@link OfflineType }
     * 
     */
    public OfflineType createOfflineType() {
        return new OfflineType();
    }

    /**
     * Create an instance of {@link OnlineType }
     * 
     */
    public OnlineType createOnlineType() {
        return new OnlineType();
    }

    /**
     * Create an instance of {@link I18NNonEmptyStringType.Value }
     * 
     */
    public I18NNonEmptyStringType.Value createI18NNonEmptyStringTypeValue() {
        return new I18NNonEmptyStringType.Value();
    }

    /**
     * Create an instance of {@link ConnectionDefinitionType.SchemeName }
     * 
     */
    public ConnectionDefinitionType.SchemeName createConnectionDefinitionTypeSchemeName() {
        return new ConnectionDefinitionType.SchemeName();
    }

    /**
     * Create an instance of {@link ConnectionDefinitionType.ParameterDefinition }
     * 
     */
    public ConnectionDefinitionType.ParameterDefinition createConnectionDefinitionTypeParameterDefinition() {
        return new ConnectionDefinitionType.ParameterDefinition();
    }

    /**
     * Create an instance of {@link ConnectionType.Parameter }
     * 
     */
    public ConnectionType.Parameter createConnectionTypeParameter() {
        return new ConnectionType.Parameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link I18NNonEmptyStringType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = I18NNonEmptyStringType.class)
    public JAXBElement<I18NNonEmptyStringType.Value> createI18NNonEmptyStringTypeValue(I18NNonEmptyStringType.Value value) {
        return new JAXBElement<I18NNonEmptyStringType.Value>(_I18NNonEmptyStringTypeValue_QNAME, I18NNonEmptyStringType.Value.class, I18NNonEmptyStringType.class, value);
    }

}
