//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.coverage_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxonomicClassificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxonomicClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taxonRankName" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="taxonRankValue" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="commonName" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="taxonomicClassification" type="{eml://ecoinformatics.org/coverage-2.1.1}TaxonomicClassificationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxonomicClassificationType", propOrder = {
    "taxonRankName",
    "taxonRankValue",
    "commonName",
    "taxonomicClassification"
})
public class TaxonomicClassificationType {

    protected String taxonRankName;
    protected String taxonRankValue;
    protected List<String> commonName;
    protected List<TaxonomicClassificationType> taxonomicClassification;

    /**
     * Gets the value of the taxonRankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxonRankName() {
        return taxonRankName;
    }

    /**
     * Sets the value of the taxonRankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxonRankName(String value) {
        this.taxonRankName = value;
    }

    /**
     * Gets the value of the taxonRankValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxonRankValue() {
        return taxonRankValue;
    }

    /**
     * Sets the value of the taxonRankValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxonRankValue(String value) {
        this.taxonRankValue = value;
    }

    /**
     * Gets the value of the commonName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commonName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommonName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCommonName() {
        if (commonName == null) {
            commonName = new ArrayList<String>();
        }
        return this.commonName;
    }

    /**
     * Gets the value of the taxonomicClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxonomicClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxonomicClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxonomicClassificationType }
     * 
     * 
     */
    public List<TaxonomicClassificationType> getTaxonomicClassification() {
        if (taxonomicClassification == null) {
            taxonomicClassification = new ArrayList<TaxonomicClassificationType>();
        }
        return this.taxonomicClassification;
    }

}
