//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.documentation_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import eml.ecoinformatics_org.text_2_1.TextType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.documentation_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tooltip_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "tooltip");
    private final static QName _Example_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "example");
    private final static QName _Description_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "description");
    private final static QName _Lineage_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "lineage");
    private final static QName _Module_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "module");
    private final static QName _Summary_QNAME = new QName("eml://ecoinformatics.org/documentation-2.1.1", "summary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.documentation_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModuleDocs }
     * 
     */
    public ModuleDocs createModuleDocs() {
        return new ModuleDocs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "tooltip")
    public JAXBElement<String> createTooltip(String value) {
        return new JAXBElement<String>(_Tooltip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "example")
    public JAXBElement<TextType> createExample(TextType value) {
        return new JAXBElement<TextType>(_Example_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "description")
    public JAXBElement<TextType> createDescription(TextType value) {
        return new JAXBElement<TextType>(_Description_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "lineage")
    public JAXBElement<String> createLineage(String value) {
        return new JAXBElement<String>(_Lineage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "module")
    public JAXBElement<String> createModule(String value) {
        return new JAXBElement<String>(_Module_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/documentation-2.1.1", name = "summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

}
