//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.access_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.access_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Access_QNAME = new QName("eml://ecoinformatics.org/access-2.1.1", "access");
    private final static QName _AccessTypeAllow_QNAME = new QName("", "allow");
    private final static QName _AccessTypeDeny_QNAME = new QName("", "deny");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.access_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessType }
     * 
     */
    public AccessType createAccessType() {
        return new AccessType();
    }

    /**
     * Create an instance of {@link AccessRule }
     * 
     */
    public AccessRule createAccessRule() {
        return new AccessRule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/access-2.1.1", name = "access")
    public JAXBElement<AccessType> createAccess(AccessType value) {
        return new JAXBElement<AccessType>(_Access_QNAME, AccessType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "allow", scope = AccessType.class)
    public JAXBElement<AccessRule> createAccessTypeAllow(AccessRule value) {
        return new JAXBElement<AccessRule>(_AccessTypeAllow_QNAME, AccessRule.class, AccessType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deny", scope = AccessType.class)
    public JAXBElement<AccessRule> createAccessTypeDeny(AccessRule value) {
        return new JAXBElement<AccessRule>(_AccessTypeDeny_QNAME, AccessRule.class, AccessType.class, value);
    }

}
