//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.software_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.software_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Software_QNAME = new QName("eml://ecoinformatics.org/software-2.1.1", "software");
    private final static QName _SoftwareTypeLicenseURL_QNAME = new QName("", "licenseURL");
    private final static QName _SoftwareTypeLicense_QNAME = new QName("", "license");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.software_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link SoftwareType.Implementation }
     * 
     */
    public SoftwareType.Implementation createSoftwareTypeImplementation() {
        return new SoftwareType.Implementation();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link SoftwareType.Implementation.Language }
     * 
     */
    public SoftwareType.Implementation.Language createSoftwareTypeImplementationLanguage() {
        return new SoftwareType.Implementation.Language();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoftwareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/software-2.1.1", name = "software")
    public JAXBElement<SoftwareType> createSoftware(SoftwareType value) {
        return new JAXBElement<SoftwareType>(_Software_QNAME, SoftwareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "licenseURL", scope = SoftwareType.class)
    public JAXBElement<String> createSoftwareTypeLicenseURL(String value) {
        return new JAXBElement<String>(_SoftwareTypeLicenseURL_QNAME, String.class, SoftwareType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "license", scope = SoftwareType.class)
    public JAXBElement<String> createSoftwareTypeLicense(String value) {
        return new JAXBElement<String>(_SoftwareTypeLicense_QNAME, String.class, SoftwareType.class, value);
    }

}
