//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "eml://ecoinformatics.org/software-2.1.1")
package eml.ecoinformatics_org.software_2_1;
