//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.text_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listitem" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="para" type="{eml://ecoinformatics.org/text-2.1.1}ParagraphType"/>
 *                   &lt;element name="itemizedlist" type="{eml://ecoinformatics.org/text-2.1.1}ListType"/>
 *                   &lt;element name="orderedlist" type="{eml://ecoinformatics.org/text-2.1.1}ListType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListType", propOrder = {
    "listitem"
})
public class ListType {

    @XmlElement(required = true)
    protected List<ListType.Listitem> listitem;

    /**
     * Gets the value of the listitem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listitem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListitem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListType.Listitem }
     * 
     * 
     */
    public List<ListType.Listitem> getListitem() {
        if (listitem == null) {
            listitem = new ArrayList<ListType.Listitem>();
        }
        return this.listitem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="para" type="{eml://ecoinformatics.org/text-2.1.1}ParagraphType"/>
     *         &lt;element name="itemizedlist" type="{eml://ecoinformatics.org/text-2.1.1}ListType"/>
     *         &lt;element name="orderedlist" type="{eml://ecoinformatics.org/text-2.1.1}ListType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paraOrItemizedlistOrOrderedlist"
    })
    public static class Listitem {

        @XmlElementRefs({
            @XmlElementRef(name = "para", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "orderedlist", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "itemizedlist", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> paraOrItemizedlistOrOrderedlist;

        /**
         * Gets the value of the paraOrItemizedlistOrOrderedlist property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paraOrItemizedlistOrOrderedlist property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParaOrItemizedlistOrOrderedlist().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ListType }{@code >}
         * {@link JAXBElement }{@code <}{@link ListType }{@code >}
         * {@link JAXBElement }{@code <}{@link ParagraphType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getParaOrItemizedlistOrOrderedlist() {
            if (paraOrItemizedlistOrOrderedlist == null) {
                paraOrItemizedlistOrOrderedlist = new ArrayList<JAXBElement<?>>();
            }
            return this.paraOrItemizedlistOrOrderedlist;
        }

    }

}
