//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.datatable_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.datatable_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataTable_QNAME = new QName("eml://ecoinformatics.org/dataTable-2.1.1", "dataTable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.datatable_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataTableType }
     * 
     */
    public DataTableType createDataTableType() {
        return new DataTableType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataTableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/dataTable-2.1.1", name = "dataTable")
    public JAXBElement<DataTableType> createDataTable(DataTableType value) {
        return new JAXBElement<DataTableType>(_DataTable_QNAME, DataTableType.class, null, value);
    }

}
