//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.project_2_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eml.ecoinformatics_org.project_2_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResearchProject_QNAME = new QName("eml://ecoinformatics.org/project-2.1.1", "researchProject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eml.ecoinformatics_org.project_2_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResearchProjectType }
     * 
     */
    public ResearchProjectType createResearchProjectType() {
        return new ResearchProjectType();
    }

    /**
     * Create an instance of {@link ResearchProjectType.StudyAreaDescription }
     * 
     */
    public ResearchProjectType.StudyAreaDescription createResearchProjectTypeStudyAreaDescription() {
        return new ResearchProjectType.StudyAreaDescription();
    }

    /**
     * Create an instance of {@link ResearchProjectType.StudyAreaDescription.Descriptor }
     * 
     */
    public ResearchProjectType.StudyAreaDescription.Descriptor createResearchProjectTypeStudyAreaDescriptionDescriptor() {
        return new ResearchProjectType.StudyAreaDescription.Descriptor();
    }

    /**
     * Create an instance of {@link ResearchProjectType.Personnel }
     * 
     */
    public ResearchProjectType.Personnel createResearchProjectTypePersonnel() {
        return new ResearchProjectType.Personnel();
    }

    /**
     * Create an instance of {@link ResearchProjectType.DesignDescription }
     * 
     */
    public ResearchProjectType.DesignDescription createResearchProjectTypeDesignDescription() {
        return new ResearchProjectType.DesignDescription();
    }

    /**
     * Create an instance of {@link ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue }
     * 
     */
    public ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue createResearchProjectTypeStudyAreaDescriptionDescriptorDescriptorValue() {
        return new ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResearchProjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "eml://ecoinformatics.org/project-2.1.1", name = "researchProject")
    public JAXBElement<ResearchProjectType> createResearchProject(ResearchProjectType value) {
        return new JAXBElement<ResearchProjectType>(_ResearchProject_QNAME, ResearchProjectType.class, null, value);
    }

}
