//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.project_2_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import eml.ecoinformatics_org.coverage_2_1.Coverage;
import eml.ecoinformatics_org.literature_2_1.CitationType;
import eml.ecoinformatics_org.party_2_1.ResponsibleParty;
import eml.ecoinformatics_org.resource_2_1.ScopeType;
import eml.ecoinformatics_org.text_2_1.TextType;


/**
 * <p>Java class for ResearchProjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResearchProjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="title" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" maxOccurs="unbounded"/>
 *           &lt;element name="personnel" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{eml://ecoinformatics.org/party-2.1.1}ResponsibleParty">
 *                   &lt;sequence maxOccurs="unbounded">
 *                     &lt;element name="role" type="{eml://ecoinformatics.org/party-2.1.1}RoleType"/>
 *                   &lt;/sequence>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="abstract" type="{eml://ecoinformatics.org/text-2.1.1}TextType" minOccurs="0"/>
 *           &lt;element name="funding" type="{eml://ecoinformatics.org/text-2.1.1}TextType" minOccurs="0"/>
 *           &lt;element name="studyAreaDescription" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="descriptor">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence maxOccurs="unbounded">
 *                               &lt;element name="descriptorValue" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;simpleContent>
 *                                     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                       &lt;attribute name="name_or_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/extension>
 *                                   &lt;/simpleContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="name" use="required" type="{eml://ecoinformatics.org/project-2.1.1}DescriptorType" />
 *                             &lt;attribute name="citableClassificationSystem" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" minOccurs="0"/>
 *                     &lt;element name="coverage" type="{eml://ecoinformatics.org/coverage-2.1.1}Coverage" minOccurs="0"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="designDescription" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="description" type="{eml://ecoinformatics.org/text-2.1.1}TextType"/>
 *                     &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" minOccurs="0"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="relatedProject" type="{eml://ecoinformatics.org/project-2.1.1}ResearchProjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;group ref="{eml://ecoinformatics.org/resource-2.1.1}ReferencesGroup"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{eml://ecoinformatics.org/resource-2.1.1}IDType" />
 *       &lt;attribute name="system" type="{eml://ecoinformatics.org/resource-2.1.1}SystemType" />
 *       &lt;attribute name="scope" type="{eml://ecoinformatics.org/resource-2.1.1}ScopeType" default="document" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResearchProjectType", propOrder = {
    "title",
    "personnel",
    "_abstract",
    "funding",
    "studyAreaDescription",
    "designDescription",
    "relatedProject",
    "references"
})
public class ResearchProjectType {

    protected List<String> title;
    protected List<ResearchProjectType.Personnel> personnel;
    @XmlElement(name = "abstract")
    protected TextType _abstract;
    protected TextType funding;
    protected ResearchProjectType.StudyAreaDescription studyAreaDescription;
    protected ResearchProjectType.DesignDescription designDescription;
    protected List<ResearchProjectType> relatedProject;
    protected eml.ecoinformatics_org.view_2_1.ViewType.References references;
    @XmlAttribute(name = "id")
    protected List<String> id;
    @XmlAttribute(name = "system")
    protected List<String> system;
    @XmlAttribute(name = "scope")
    protected ScopeType scope;

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTitle() {
        if (title == null) {
            title = new ArrayList<String>();
        }
        return this.title;
    }

    /**
     * Gets the value of the personnel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonnel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResearchProjectType.Personnel }
     * 
     * 
     */
    public List<ResearchProjectType.Personnel> getPersonnel() {
        if (personnel == null) {
            personnel = new ArrayList<ResearchProjectType.Personnel>();
        }
        return this.personnel;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setAbstract(TextType value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the funding property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getFunding() {
        return funding;
    }

    /**
     * Sets the value of the funding property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setFunding(TextType value) {
        this.funding = value;
    }

    /**
     * Gets the value of the studyAreaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchProjectType.StudyAreaDescription }
     *     
     */
    public ResearchProjectType.StudyAreaDescription getStudyAreaDescription() {
        return studyAreaDescription;
    }

    /**
     * Sets the value of the studyAreaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchProjectType.StudyAreaDescription }
     *     
     */
    public void setStudyAreaDescription(ResearchProjectType.StudyAreaDescription value) {
        this.studyAreaDescription = value;
    }

    /**
     * Gets the value of the designDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchProjectType.DesignDescription }
     *     
     */
    public ResearchProjectType.DesignDescription getDesignDescription() {
        return designDescription;
    }

    /**
     * Sets the value of the designDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchProjectType.DesignDescription }
     *     
     */
    public void setDesignDescription(ResearchProjectType.DesignDescription value) {
        this.designDescription = value;
    }

    /**
     * Gets the value of the relatedProject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedProject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResearchProjectType }
     * 
     * 
     */
    public List<ResearchProjectType> getRelatedProject() {
        if (relatedProject == null) {
            relatedProject = new ArrayList<ResearchProjectType>();
        }
        return this.relatedProject;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link eml.ecoinformatics_org.view_2_1.ViewType.References }
     *     
     */
    public eml.ecoinformatics_org.view_2_1.ViewType.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link eml.ecoinformatics_org.view_2_1.ViewType.References }
     *     
     */
    public void setReferences(eml.ecoinformatics_org.view_2_1.ViewType.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getId() {
        if (id == null) {
            id = new ArrayList<String>();
        }
        return this.id;
    }

    /**
     * Gets the value of the system property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the system property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSystem() {
        if (system == null) {
            system = new ArrayList<String>();
        }
        return this.system;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link ScopeType }
     *     
     */
    public ScopeType getScope() {
        if (scope == null) {
            return ScopeType.DOCUMENT;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopeType }
     *     
     */
    public void setScope(ScopeType value) {
        this.scope = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="description" type="{eml://ecoinformatics.org/text-2.1.1}TextType"/>
     *         &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "descriptionOrCitation"
    })
    public static class DesignDescription {

        @XmlElements({
            @XmlElement(name = "description", type = TextType.class),
            @XmlElement(name = "citation", type = CitationType.class)
        })
        protected List<Object> descriptionOrCitation;

        /**
         * Gets the value of the descriptionOrCitation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the descriptionOrCitation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDescriptionOrCitation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextType }
         * {@link CitationType }
         * 
         * 
         */
        public List<Object> getDescriptionOrCitation() {
            if (descriptionOrCitation == null) {
                descriptionOrCitation = new ArrayList<Object>();
            }
            return this.descriptionOrCitation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{eml://ecoinformatics.org/party-2.1.1}ResponsibleParty">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="role" type="{eml://ecoinformatics.org/party-2.1.1}RoleType"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "role"
    })
    public static class Personnel
        extends ResponsibleParty
    {

        @XmlElement(required = true)
        protected List<String> role;

        /**
         * Gets the value of the role property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the role property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRole().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRole() {
            if (role == null) {
                role = new ArrayList<String>();
            }
            return this.role;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="descriptor">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="descriptorValue" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="name_or_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" use="required" type="{eml://ecoinformatics.org/project-2.1.1}DescriptorType" />
     *                 &lt;attribute name="citableClassificationSystem" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" minOccurs="0"/>
     *         &lt;element name="coverage" type="{eml://ecoinformatics.org/coverage-2.1.1}Coverage" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "descriptorOrCitationOrCoverage"
    })
    public static class StudyAreaDescription {

        @XmlElements({
            @XmlElement(name = "descriptor", type = ResearchProjectType.StudyAreaDescription.Descriptor.class),
            @XmlElement(name = "citation", type = CitationType.class),
            @XmlElement(name = "coverage", type = Coverage.class)
        })
        protected List<Object> descriptorOrCitationOrCoverage;

        /**
         * Gets the value of the descriptorOrCitationOrCoverage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the descriptorOrCitationOrCoverage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDescriptorOrCitationOrCoverage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResearchProjectType.StudyAreaDescription.Descriptor }
         * {@link CitationType }
         * {@link Coverage }
         * 
         * 
         */
        public List<Object> getDescriptorOrCitationOrCoverage() {
            if (descriptorOrCitationOrCoverage == null) {
                descriptorOrCitationOrCoverage = new ArrayList<Object>();
            }
            return this.descriptorOrCitationOrCoverage;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="descriptorValue" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="name_or_id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="citation" type="{eml://ecoinformatics.org/literature-2.1.1}CitationType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{eml://ecoinformatics.org/project-2.1.1}DescriptorType" />
         *       &lt;attribute name="citableClassificationSystem" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "descriptorValueAndCitation"
        })
        public static class Descriptor {

            @XmlElements({
                @XmlElement(name = "descriptorValue", required = true, type = ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue.class),
                @XmlElement(name = "citation", required = true, type = CitationType.class)
            })
            protected List<Object> descriptorValueAndCitation;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "citableClassificationSystem", required = true)
            protected boolean citableClassificationSystem;

            /**
             * Gets the value of the descriptorValueAndCitation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the descriptorValueAndCitation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDescriptorValueAndCitation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ResearchProjectType.StudyAreaDescription.Descriptor.DescriptorValue }
             * {@link CitationType }
             * 
             * 
             */
            public List<Object> getDescriptorValueAndCitation() {
                if (descriptorValueAndCitation == null) {
                    descriptorValueAndCitation = new ArrayList<Object>();
                }
                return this.descriptorValueAndCitation;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the citableClassificationSystem property.
             * 
             */
            public boolean isCitableClassificationSystem() {
                return citableClassificationSystem;
            }

            /**
             * Sets the value of the citableClassificationSystem property.
             * 
             */
            public void setCitableClassificationSystem(boolean value) {
                this.citableClassificationSystem = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="name_or_id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class DescriptorValue {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "name_or_id")
                protected String nameOrId;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the nameOrId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNameOrId() {
                    return nameOrId;
                }

                /**
                 * Sets the value of the nameOrId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNameOrId(String value) {
                    this.nameOrId = value;
                }

            }

        }

    }

}
