//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.spatialraster_2_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CellValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CellValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Values"/>
 *     &lt;enumeration value="Coded"/>
 *     &lt;enumeration value="RGB"/>
 *     &lt;enumeration value="Codes"/>
 *     &lt;enumeration value="HIS"/>
 *     &lt;enumeration value="HLS"/>
 *     &lt;enumeration value="tekHVC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CellValueType")
@XmlEnum
public enum CellValueType {

    @XmlEnumValue("Values")
    VALUES("Values"),
    @XmlEnumValue("Coded")
    CODED("Coded"),
    RGB("RGB"),
    @XmlEnumValue("Codes")
    CODES("Codes"),
    HIS("HIS"),
    HLS("HLS"),
    @XmlEnumValue("tekHVC")
    TEK_HVC("tekHVC");
    private final String value;

    CellValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CellValueType fromValue(String v) {
        for (CellValueType c: CellValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
