//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 05:13:02 PM MST 
//


package eml.ecoinformatics_org.spatialraster_2_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eml.ecoinformatics_org.attribute_2_1.AttributeListType;
import eml.ecoinformatics_org.constraint_2_1.ConstraintType;
import eml.ecoinformatics_org.coverage_2_1.Coverage;
import eml.ecoinformatics_org.methods_2_1.MethodsType;
import eml.ecoinformatics_org.physical_2_1.PhysicalType;
import eml.ecoinformatics_org.resource_2_1.ScopeType;
import eml.ecoinformatics_org.spatialreference_2_1.SpatialReferenceType;
import eml.ecoinformatics_org.text_2_1.TextType;


/**
 * <p>Java class for SpatialRasterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpatialRasterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;group ref="{eml://ecoinformatics.org/entity-2.1.1}EntityGroup"/>
 *           &lt;element name="attributeList" type="{eml://ecoinformatics.org/attribute-2.1.1}AttributeListType"/>
 *           &lt;element name="constraint" type="{eml://ecoinformatics.org/constraint-2.1.1}ConstraintType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="spatialReference" type="{eml://ecoinformatics.org/spatialReference-2.1.1}SpatialReferenceType"/>
 *           &lt;element name="georeferenceInfo" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element name="cornerPoint" maxOccurs="4">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="xCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="yCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="pointInPixel">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="upperLeft"/>
 *                                     &lt;enumeration value="upperRight"/>
 *                                     &lt;enumeration value="lowerRight"/>
 *                                     &lt;enumeration value="lowerLeft"/>
 *                                     &lt;enumeration value="center"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="corner" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}rasterOriginType"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="controlPoint" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="column" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="row" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                               &lt;element name="xCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="yCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="pointInPixel">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="upperLeft"/>
 *                                     &lt;enumeration value="upperRight"/>
 *                                     &lt;enumeration value="lowerRight"/>
 *                                     &lt;enumeration value="lowerLeft"/>
 *                                     &lt;enumeration value="center"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="bilinearFit">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="xIntercept" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="xSlope" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="yIntercept" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                               &lt;element name="ySlope" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="horizontalAccuracy" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}DataQuality"/>
 *           &lt;element name="verticalAccuracy" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}DataQuality"/>
 *           &lt;element name="cellSizeXDirection" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="cellSizeYDirection" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="numberOfBands" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="rasterOrigin" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}rasterOriginType"/>
 *           &lt;element name="rows" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *           &lt;element name="columns" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType"/>
 *           &lt;element name="verticals" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="cellGeometry" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}CellGeometryType"/>
 *           &lt;element name="toneGradation" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *           &lt;element name="scaleFactor" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *           &lt;element name="offset" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *           &lt;element name="imageDescription" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="illuminationElevationAngle" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                     &lt;element name="illuminationAzimuthAngle" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                     &lt;element name="imageOrientationAngle" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                     &lt;element name="imagingCondition" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}ImagingConditionCode" minOccurs="0"/>
 *                     &lt;element name="imageQualityCode" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *                     &lt;element name="cloudCoverPercentage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                     &lt;element name="preProcessingTypeCode" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
 *                     &lt;element name="compressionGenerationQuality" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                     &lt;element name="triangulationIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="radiometricDataAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="cameraCalibrationInformationAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="filmDistortionInformationAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="lensDistortionInformationAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                     &lt;element name="bandDescription" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}BandType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;group ref="{eml://ecoinformatics.org/resource-2.1.1}ReferencesGroup"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{eml://ecoinformatics.org/resource-2.1.1}IDType" />
 *       &lt;attribute name="system" type="{eml://ecoinformatics.org/resource-2.1.1}SystemType" />
 *       &lt;attribute name="scope" type="{eml://ecoinformatics.org/resource-2.1.1}ScopeType" default="document" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpatialRasterType", propOrder = {
    "alternateIdentifier",
    "entityName",
    "entityDescription",
    "physical",
    "coverage",
    "methods",
    "additionalInfo",
    "attributeList",
    "constraint",
    "spatialReference",
    "georeferenceInfo",
    "horizontalAccuracy",
    "verticalAccuracy",
    "cellSizeXDirection",
    "cellSizeYDirection",
    "numberOfBands",
    "rasterOrigin",
    "rows",
    "columns",
    "verticals",
    "cellGeometry",
    "toneGradation",
    "scaleFactor",
    "offset",
    "imageDescription",
    "references"
})
public class SpatialRasterType {

    protected List<eml.ecoinformatics_org.view_2_1.ViewType.AlternateIdentifier> alternateIdentifier;
    protected String entityName;
    protected String entityDescription;
    protected List<PhysicalType> physical;
    protected Coverage coverage;
    protected MethodsType methods;
    protected List<TextType> additionalInfo;
    protected AttributeListType attributeList;
    protected List<ConstraintType> constraint;
    protected SpatialReferenceType spatialReference;
    protected SpatialRasterType.GeoreferenceInfo georeferenceInfo;
    protected DataQuality horizontalAccuracy;
    protected DataQuality verticalAccuracy;
    protected Object cellSizeXDirection;
    protected Object cellSizeYDirection;
    protected Object numberOfBands;
    protected RasterOriginType rasterOrigin;
    protected String rows;
    protected String columns;
    protected Object verticals;
    protected CellGeometryType cellGeometry;
    protected BigInteger toneGradation;
    protected String scaleFactor;
    protected String offset;
    protected SpatialRasterType.ImageDescription imageDescription;
    protected eml.ecoinformatics_org.view_2_1.ViewType.References references;
    @XmlAttribute(name = "id")
    protected List<String> id;
    @XmlAttribute(name = "system")
    protected List<String> system;
    @XmlAttribute(name = "scope")
    protected ScopeType scope;

    /**
     * Gets the value of the alternateIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link eml.ecoinformatics_org.view_2_1.ViewType.AlternateIdentifier }
     * 
     * 
     */
    public List<eml.ecoinformatics_org.view_2_1.ViewType.AlternateIdentifier> getAlternateIdentifier() {
        if (alternateIdentifier == null) {
            alternateIdentifier = new ArrayList<eml.ecoinformatics_org.view_2_1.ViewType.AlternateIdentifier>();
        }
        return this.alternateIdentifier;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the entityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityDescription() {
        return entityDescription;
    }

    /**
     * Sets the value of the entityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityDescription(String value) {
        this.entityDescription = value;
    }

    /**
     * Gets the value of the physical property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physical property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysical().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalType }
     * 
     * 
     */
    public List<PhysicalType> getPhysical() {
        if (physical == null) {
            physical = new ArrayList<PhysicalType>();
        }
        return this.physical;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link Coverage }
     *     
     */
    public Coverage getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coverage }
     *     
     */
    public void setCoverage(Coverage value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link MethodsType }
     *     
     */
    public MethodsType getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodsType }
     *     
     */
    public void setMethods(MethodsType value) {
        this.methods = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getAdditionalInfo() {
        if (additionalInfo == null) {
            additionalInfo = new ArrayList<TextType>();
        }
        return this.additionalInfo;
    }

    /**
     * Gets the value of the attributeList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeListType }
     *     
     */
    public AttributeListType getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeListType }
     *     
     */
    public void setAttributeList(AttributeListType value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstraintType }
     * 
     * 
     */
    public List<ConstraintType> getConstraint() {
        if (constraint == null) {
            constraint = new ArrayList<ConstraintType>();
        }
        return this.constraint;
    }

    /**
     * Gets the value of the spatialReference property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialReferenceType }
     *     
     */
    public SpatialReferenceType getSpatialReference() {
        return spatialReference;
    }

    /**
     * Sets the value of the spatialReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialReferenceType }
     *     
     */
    public void setSpatialReference(SpatialReferenceType value) {
        this.spatialReference = value;
    }

    /**
     * Gets the value of the georeferenceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialRasterType.GeoreferenceInfo }
     *     
     */
    public SpatialRasterType.GeoreferenceInfo getGeoreferenceInfo() {
        return georeferenceInfo;
    }

    /**
     * Sets the value of the georeferenceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialRasterType.GeoreferenceInfo }
     *     
     */
    public void setGeoreferenceInfo(SpatialRasterType.GeoreferenceInfo value) {
        this.georeferenceInfo = value;
    }

    /**
     * Gets the value of the horizontalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link DataQuality }
     *     
     */
    public DataQuality getHorizontalAccuracy() {
        return horizontalAccuracy;
    }

    /**
     * Sets the value of the horizontalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataQuality }
     *     
     */
    public void setHorizontalAccuracy(DataQuality value) {
        this.horizontalAccuracy = value;
    }

    /**
     * Gets the value of the verticalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link DataQuality }
     *     
     */
    public DataQuality getVerticalAccuracy() {
        return verticalAccuracy;
    }

    /**
     * Sets the value of the verticalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataQuality }
     *     
     */
    public void setVerticalAccuracy(DataQuality value) {
        this.verticalAccuracy = value;
    }

    /**
     * Gets the value of the cellSizeXDirection property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCellSizeXDirection() {
        return cellSizeXDirection;
    }

    /**
     * Sets the value of the cellSizeXDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCellSizeXDirection(Object value) {
        this.cellSizeXDirection = value;
    }

    /**
     * Gets the value of the cellSizeYDirection property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCellSizeYDirection() {
        return cellSizeYDirection;
    }

    /**
     * Sets the value of the cellSizeYDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCellSizeYDirection(Object value) {
        this.cellSizeYDirection = value;
    }

    /**
     * Gets the value of the numberOfBands property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNumberOfBands() {
        return numberOfBands;
    }

    /**
     * Sets the value of the numberOfBands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNumberOfBands(Object value) {
        this.numberOfBands = value;
    }

    /**
     * Gets the value of the rasterOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link RasterOriginType }
     *     
     */
    public RasterOriginType getRasterOrigin() {
        return rasterOrigin;
    }

    /**
     * Sets the value of the rasterOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RasterOriginType }
     *     
     */
    public void setRasterOrigin(RasterOriginType value) {
        this.rasterOrigin = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRows(String value) {
        this.rows = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumns(String value) {
        this.columns = value;
    }

    /**
     * Gets the value of the verticals property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVerticals() {
        return verticals;
    }

    /**
     * Sets the value of the verticals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVerticals(Object value) {
        this.verticals = value;
    }

    /**
     * Gets the value of the cellGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link CellGeometryType }
     *     
     */
    public CellGeometryType getCellGeometry() {
        return cellGeometry;
    }

    /**
     * Sets the value of the cellGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link CellGeometryType }
     *     
     */
    public void setCellGeometry(CellGeometryType value) {
        this.cellGeometry = value;
    }

    /**
     * Gets the value of the toneGradation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getToneGradation() {
        return toneGradation;
    }

    /**
     * Sets the value of the toneGradation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setToneGradation(BigInteger value) {
        this.toneGradation = value;
    }

    /**
     * Gets the value of the scaleFactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaleFactor() {
        return scaleFactor;
    }

    /**
     * Sets the value of the scaleFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaleFactor(String value) {
        this.scaleFactor = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffset(String value) {
        this.offset = value;
    }

    /**
     * Gets the value of the imageDescription property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialRasterType.ImageDescription }
     *     
     */
    public SpatialRasterType.ImageDescription getImageDescription() {
        return imageDescription;
    }

    /**
     * Sets the value of the imageDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialRasterType.ImageDescription }
     *     
     */
    public void setImageDescription(SpatialRasterType.ImageDescription value) {
        this.imageDescription = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link eml.ecoinformatics_org.view_2_1.ViewType.References }
     *     
     */
    public eml.ecoinformatics_org.view_2_1.ViewType.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link eml.ecoinformatics_org.view_2_1.ViewType.References }
     *     
     */
    public void setReferences(eml.ecoinformatics_org.view_2_1.ViewType.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getId() {
        if (id == null) {
            id = new ArrayList<String>();
        }
        return this.id;
    }

    /**
     * Gets the value of the system property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the system property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSystem() {
        if (system == null) {
            system = new ArrayList<String>();
        }
        return this.system;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link ScopeType }
     *     
     */
    public ScopeType getScope() {
        if (scope == null) {
            return ScopeType.DOCUMENT;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopeType }
     *     
     */
    public void setScope(ScopeType value) {
        this.scope = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="cornerPoint" maxOccurs="4">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="xCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="yCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="pointInPixel">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="upperLeft"/>
     *                         &lt;enumeration value="upperRight"/>
     *                         &lt;enumeration value="lowerRight"/>
     *                         &lt;enumeration value="lowerLeft"/>
     *                         &lt;enumeration value="center"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="corner" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}rasterOriginType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="controlPoint" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="column" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="row" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="xCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="yCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="pointInPixel">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="upperLeft"/>
     *                         &lt;enumeration value="upperRight"/>
     *                         &lt;enumeration value="lowerRight"/>
     *                         &lt;enumeration value="lowerLeft"/>
     *                         &lt;enumeration value="center"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="bilinearFit">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="xIntercept" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="xSlope" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="yIntercept" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="ySlope" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cornerPoint",
        "controlPoint",
        "bilinearFit"
    })
    public static class GeoreferenceInfo {

        protected List<SpatialRasterType.GeoreferenceInfo.CornerPoint> cornerPoint;
        protected List<SpatialRasterType.GeoreferenceInfo.ControlPoint> controlPoint;
        protected SpatialRasterType.GeoreferenceInfo.BilinearFit bilinearFit;

        /**
         * Gets the value of the cornerPoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cornerPoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCornerPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SpatialRasterType.GeoreferenceInfo.CornerPoint }
         * 
         * 
         */
        public List<SpatialRasterType.GeoreferenceInfo.CornerPoint> getCornerPoint() {
            if (cornerPoint == null) {
                cornerPoint = new ArrayList<SpatialRasterType.GeoreferenceInfo.CornerPoint>();
            }
            return this.cornerPoint;
        }

        /**
         * Gets the value of the controlPoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the controlPoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getControlPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SpatialRasterType.GeoreferenceInfo.ControlPoint }
         * 
         * 
         */
        public List<SpatialRasterType.GeoreferenceInfo.ControlPoint> getControlPoint() {
            if (controlPoint == null) {
                controlPoint = new ArrayList<SpatialRasterType.GeoreferenceInfo.ControlPoint>();
            }
            return this.controlPoint;
        }

        /**
         * Gets the value of the bilinearFit property.
         * 
         * @return
         *     possible object is
         *     {@link SpatialRasterType.GeoreferenceInfo.BilinearFit }
         *     
         */
        public SpatialRasterType.GeoreferenceInfo.BilinearFit getBilinearFit() {
            return bilinearFit;
        }

        /**
         * Sets the value of the bilinearFit property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpatialRasterType.GeoreferenceInfo.BilinearFit }
         *     
         */
        public void setBilinearFit(SpatialRasterType.GeoreferenceInfo.BilinearFit value) {
            this.bilinearFit = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="xIntercept" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="xSlope" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="yIntercept" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="ySlope" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xIntercept",
            "xSlope",
            "yIntercept",
            "ySlope"
        })
        public static class BilinearFit {

            protected float xIntercept;
            protected float xSlope;
            protected float yIntercept;
            protected float ySlope;

            /**
             * Gets the value of the xIntercept property.
             * 
             */
            public float getXIntercept() {
                return xIntercept;
            }

            /**
             * Sets the value of the xIntercept property.
             * 
             */
            public void setXIntercept(float value) {
                this.xIntercept = value;
            }

            /**
             * Gets the value of the xSlope property.
             * 
             */
            public float getXSlope() {
                return xSlope;
            }

            /**
             * Sets the value of the xSlope property.
             * 
             */
            public void setXSlope(float value) {
                this.xSlope = value;
            }

            /**
             * Gets the value of the yIntercept property.
             * 
             */
            public float getYIntercept() {
                return yIntercept;
            }

            /**
             * Sets the value of the yIntercept property.
             * 
             */
            public void setYIntercept(float value) {
                this.yIntercept = value;
            }

            /**
             * Gets the value of the ySlope property.
             * 
             */
            public float getYSlope() {
                return ySlope;
            }

            /**
             * Sets the value of the ySlope property.
             * 
             */
            public void setYSlope(float value) {
                this.ySlope = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="column" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="row" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="xCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="yCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="pointInPixel">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="upperLeft"/>
         *               &lt;enumeration value="upperRight"/>
         *               &lt;enumeration value="lowerRight"/>
         *               &lt;enumeration value="lowerLeft"/>
         *               &lt;enumeration value="center"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "column",
            "row",
            "xCoordinate",
            "yCoordinate",
            "pointInPixel"
        })
        public static class ControlPoint {

            protected int column;
            protected int row;
            protected float xCoordinate;
            protected float yCoordinate;
            @XmlElement(required = true)
            protected String pointInPixel;

            /**
             * Gets the value of the column property.
             * 
             */
            public int getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             */
            public void setColumn(int value) {
                this.column = value;
            }

            /**
             * Gets the value of the row property.
             * 
             */
            public int getRow() {
                return row;
            }

            /**
             * Sets the value of the row property.
             * 
             */
            public void setRow(int value) {
                this.row = value;
            }

            /**
             * Gets the value of the xCoordinate property.
             * 
             */
            public float getXCoordinate() {
                return xCoordinate;
            }

            /**
             * Sets the value of the xCoordinate property.
             * 
             */
            public void setXCoordinate(float value) {
                this.xCoordinate = value;
            }

            /**
             * Gets the value of the yCoordinate property.
             * 
             */
            public float getYCoordinate() {
                return yCoordinate;
            }

            /**
             * Sets the value of the yCoordinate property.
             * 
             */
            public void setYCoordinate(float value) {
                this.yCoordinate = value;
            }

            /**
             * Gets the value of the pointInPixel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPointInPixel() {
                return pointInPixel;
            }

            /**
             * Sets the value of the pointInPixel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPointInPixel(String value) {
                this.pointInPixel = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="xCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="yCoordinate" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="pointInPixel">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="upperLeft"/>
         *               &lt;enumeration value="upperRight"/>
         *               &lt;enumeration value="lowerRight"/>
         *               &lt;enumeration value="lowerLeft"/>
         *               &lt;enumeration value="center"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="corner" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}rasterOriginType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xCoordinate",
            "yCoordinate",
            "pointInPixel",
            "corner"
        })
        public static class CornerPoint {

            protected float xCoordinate;
            protected float yCoordinate;
            @XmlElement(required = true)
            protected String pointInPixel;
            @XmlElement(required = true)
            protected RasterOriginType corner;

            /**
             * Gets the value of the xCoordinate property.
             * 
             */
            public float getXCoordinate() {
                return xCoordinate;
            }

            /**
             * Sets the value of the xCoordinate property.
             * 
             */
            public void setXCoordinate(float value) {
                this.xCoordinate = value;
            }

            /**
             * Gets the value of the yCoordinate property.
             * 
             */
            public float getYCoordinate() {
                return yCoordinate;
            }

            /**
             * Sets the value of the yCoordinate property.
             * 
             */
            public void setYCoordinate(float value) {
                this.yCoordinate = value;
            }

            /**
             * Gets the value of the pointInPixel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPointInPixel() {
                return pointInPixel;
            }

            /**
             * Sets the value of the pointInPixel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPointInPixel(String value) {
                this.pointInPixel = value;
            }

            /**
             * Gets the value of the corner property.
             * 
             * @return
             *     possible object is
             *     {@link RasterOriginType }
             *     
             */
            public RasterOriginType getCorner() {
                return corner;
            }

            /**
             * Sets the value of the corner property.
             * 
             * @param value
             *     allowed object is
             *     {@link RasterOriginType }
             *     
             */
            public void setCorner(RasterOriginType value) {
                this.corner = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="illuminationElevationAngle" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="illuminationAzimuthAngle" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="imageOrientationAngle" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="imagingCondition" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}ImagingConditionCode" minOccurs="0"/>
     *         &lt;element name="imageQualityCode" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
     *         &lt;element name="cloudCoverPercentage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="preProcessingTypeCode" type="{eml://ecoinformatics.org/resource-2.1.1}NonEmptyStringType" minOccurs="0"/>
     *         &lt;element name="compressionGenerationQuality" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="triangulationIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="radiometricDataAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="cameraCalibrationInformationAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="filmDistortionInformationAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="lensDistortionInformationAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="bandDescription" type="{eml://ecoinformatics.org/spatialRaster-2.1.1}BandType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "illuminationElevationAngle",
        "illuminationAzimuthAngle",
        "imageOrientationAngle",
        "imagingCondition",
        "imageQualityCode",
        "cloudCoverPercentage",
        "preProcessingTypeCode",
        "compressionGenerationQuality",
        "triangulationIndicator",
        "radiometricDataAvailability",
        "cameraCalibrationInformationAvailability",
        "filmDistortionInformationAvailability",
        "lensDistortionInformationAvailability",
        "bandDescription"
    })
    public static class ImageDescription {

        protected Float illuminationElevationAngle;
        protected Float illuminationAzimuthAngle;
        protected Float imageOrientationAngle;
        protected ImagingConditionCode imagingCondition;
        protected String imageQualityCode;
        protected Float cloudCoverPercentage;
        protected String preProcessingTypeCode;
        protected BigInteger compressionGenerationQuality;
        protected Boolean triangulationIndicator;
        protected Boolean radiometricDataAvailability;
        protected Boolean cameraCalibrationInformationAvailability;
        protected Boolean filmDistortionInformationAvailability;
        protected Boolean lensDistortionInformationAvailability;
        protected List<BandType> bandDescription;

        /**
         * Gets the value of the illuminationElevationAngle property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getIlluminationElevationAngle() {
            return illuminationElevationAngle;
        }

        /**
         * Sets the value of the illuminationElevationAngle property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setIlluminationElevationAngle(Float value) {
            this.illuminationElevationAngle = value;
        }

        /**
         * Gets the value of the illuminationAzimuthAngle property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getIlluminationAzimuthAngle() {
            return illuminationAzimuthAngle;
        }

        /**
         * Sets the value of the illuminationAzimuthAngle property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setIlluminationAzimuthAngle(Float value) {
            this.illuminationAzimuthAngle = value;
        }

        /**
         * Gets the value of the imageOrientationAngle property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getImageOrientationAngle() {
            return imageOrientationAngle;
        }

        /**
         * Sets the value of the imageOrientationAngle property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setImageOrientationAngle(Float value) {
            this.imageOrientationAngle = value;
        }

        /**
         * Gets the value of the imagingCondition property.
         * 
         * @return
         *     possible object is
         *     {@link ImagingConditionCode }
         *     
         */
        public ImagingConditionCode getImagingCondition() {
            return imagingCondition;
        }

        /**
         * Sets the value of the imagingCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImagingConditionCode }
         *     
         */
        public void setImagingCondition(ImagingConditionCode value) {
            this.imagingCondition = value;
        }

        /**
         * Gets the value of the imageQualityCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageQualityCode() {
            return imageQualityCode;
        }

        /**
         * Sets the value of the imageQualityCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageQualityCode(String value) {
            this.imageQualityCode = value;
        }

        /**
         * Gets the value of the cloudCoverPercentage property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getCloudCoverPercentage() {
            return cloudCoverPercentage;
        }

        /**
         * Sets the value of the cloudCoverPercentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setCloudCoverPercentage(Float value) {
            this.cloudCoverPercentage = value;
        }

        /**
         * Gets the value of the preProcessingTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreProcessingTypeCode() {
            return preProcessingTypeCode;
        }

        /**
         * Sets the value of the preProcessingTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreProcessingTypeCode(String value) {
            this.preProcessingTypeCode = value;
        }

        /**
         * Gets the value of the compressionGenerationQuality property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCompressionGenerationQuality() {
            return compressionGenerationQuality;
        }

        /**
         * Sets the value of the compressionGenerationQuality property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCompressionGenerationQuality(BigInteger value) {
            this.compressionGenerationQuality = value;
        }

        /**
         * Gets the value of the triangulationIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isTriangulationIndicator() {
            return triangulationIndicator;
        }

        /**
         * Sets the value of the triangulationIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setTriangulationIndicator(Boolean value) {
            this.triangulationIndicator = value;
        }

        /**
         * Gets the value of the radiometricDataAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRadiometricDataAvailability() {
            return radiometricDataAvailability;
        }

        /**
         * Sets the value of the radiometricDataAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRadiometricDataAvailability(Boolean value) {
            this.radiometricDataAvailability = value;
        }

        /**
         * Gets the value of the cameraCalibrationInformationAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isCameraCalibrationInformationAvailability() {
            return cameraCalibrationInformationAvailability;
        }

        /**
         * Sets the value of the cameraCalibrationInformationAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCameraCalibrationInformationAvailability(Boolean value) {
            this.cameraCalibrationInformationAvailability = value;
        }

        /**
         * Gets the value of the filmDistortionInformationAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFilmDistortionInformationAvailability() {
            return filmDistortionInformationAvailability;
        }

        /**
         * Sets the value of the filmDistortionInformationAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFilmDistortionInformationAvailability(Boolean value) {
            this.filmDistortionInformationAvailability = value;
        }

        /**
         * Gets the value of the lensDistortionInformationAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLensDistortionInformationAvailability() {
            return lensDistortionInformationAvailability;
        }

        /**
         * Sets the value of the lensDistortionInformationAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLensDistortionInformationAvailability(Boolean value) {
            this.lensDistortionInformationAvailability = value;
        }

        /**
         * Gets the value of the bandDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bandDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBandDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BandType }
         * 
         * 
         */
        public List<BandType> getBandDescription() {
            if (bandDescription == null) {
                bandDescription = new ArrayList<BandType>();
            }
            return this.bandDescription;
        }

    }

}
